title: Ana tests Lab slides
author: ana
email: ana@
description: > # this means to ignore newlines until "baseurl:"
  This is a test site for the lab.
theme: minima

# social links
twitter_username: aanatecture # DO NOT include the @ character, or else the build will fail!
github_username:  anatecture # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
